1. Импорт библиотеки NumPy с общепринятым сокращением

In [2]:
import numpy as np

2. Примеры создания массивов

In [3]:
#Создание массива
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [4]:
#Создание массива, заполненного нулями
a = np.zeros((2, 3))
a

In [5]:
#Создание массива, заполненного единицами
a = np.ones((2, 2, 3))
a

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [7]:
#Создание единиченой матрицы
a = np.eye(4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [8]:
#Создание массива, заполненного мусором
a = np.empty((2, 3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
#Создание последовательности
a = np.arange(10, 30, 4)
a

array([10, 14, 18, 22, 26])

In [13]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
a = np.arange(10, -10, -2)
a

array([10,  8,  6,  4,  2,  0, -2, -4, -6, -8])

3. Демонстрация атрибутов

In [15]:
# Показ формы массива
a = np.array([[1, 2], [3, 4]])
np.shape(a)

(2, 2, 3)

In [16]:
# Показ типа массива
a = np.array([[1, 2], [3, 4]])
type(a)

numpy.ndarray

4. Примеры индексирования и срезов

In [28]:
#Получение одного элемента массива
a = np.arange(15)
print(a)
a[1]

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


np.int64(1)

In [29]:
#Срез с 2 по 5 элемент
a[2:6]

array([2, 3, 4, 5])

In [32]:
#Выбрать конкретные элементы по индексу
a[[2, 6]]

array([2, 6])

In [33]:
#Выбрать конкретные элементы по индексу, можно любой порядок
a[[7, 1, 4]]

array([7, 1, 4])

In [35]:
#Можно повторять значения
a[[1, 2, 1, 7, 1]]

array([1, 2, 1, 7, 1])

In [ ]:
#Взять последний элемент
a[-1]

Работа с многомерными массивами

In [36]:
b = np.array([[1, 1.5, 2, 2.5],
              [3, 3.5, 4, 4.5],
              [5, 5.5, 6, 6.5]])
b

array([[1. , 1.5, 2. , 2.5],
       [3. , 3.5, 4. , 4.5],
       [5. , 5.5, 6. , 6.5]])

In [40]:
#Обращение к элементу
print(b[0, 1])
print(b[(0, 1)])
#Срез подмассива
print(b[[0, 1]])

1.5
1.5
[[1.  1.5 2.  2.5]
 [3.  3.5 4.  4.5]]


In [44]:
#Срез подмассива
b[[0, 2], 0]
#Взятие конкретных элементов
b[[0, 2], [1, 3]]

array([1.5, 6.5])

In [49]:
#Взятие двумерного подмассива
b[1:3, 0:2]

array([[3. , 3.5],
       [5. , 5.5]])

In [55]:
#Взятие одномерного подмассива
b[1:2, 0:2]

array([[3. , 3.5]])

In [53]:
#Взять конкретный столбец целиком
b[:, 1]

array([1.5, 3.5, 5.5])

In [54]:
#Взять строку целиком
print(b[1])
print(b[1, :])

[3.  3.5 4.  4.5]
[3.  3.5 4.  4.5]


In [56]:
#Взять весь массив
b[:]

array([[1. , 1.5, 2. , 2.5],
       [3. , 3.5, 4. , 4.5],
       [5. , 5.5, 6. , 6.5]])

In [58]:
#Выбрать первые 2 строки, указывается идекс, который уже не входит
b[:2]

array([[1. , 1.5, 2. , 2.5],
       [3. , 3.5, 4. , 4.5]])

In [59]:
#Выбрать первые 2 строки, указывается идекс, который уже не входит
# :: - все
b[:2, ::]

array([[1. , 1.5, 2. , 2.5],
       [3. , 3.5, 4. , 4.5]])

In [60]:
#Выбрать первые 2 строки и столбцы со 2 индекса
b[:2, 2:]

array([[2. , 2.5],
       [4. , 4.5]])

In [64]:
#Берет первую строку из получившегося среза
b[0:2][0]

array([1. , 1.5, 2. , 2.5])

In [68]:
#Создание массива
c = np.empty((2, 3, 3, 3))
#Выбрать элементы из полседней оси
c[..., 2]

array([[[6.20651817e+223, 1.30371153e-076, 2.13780573e+161],
        [1.11783491e+253, 1.27587166e-152, 1.12040361e+200],
        [6.01432367e+175, 7.86514916e+276, 1.50818256e+161]],

       [[2.47379808e-091, 4.03249812e+228, 7.34629040e+223],
        [1.52811616e+228, 2.39786819e-258, 9.75388064e+199],
        [3.86585430e+233, 6.77023426e+223, 1.21697542e-152]]])

5. Примеры векторных операций и базовых статистик

In [69]:
a = np.arange(2, 20, 2)
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [70]:
b = np.arange(10, 100, 10)
b

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [71]:
#Поэлментное сложение массивов, важно, чтобы были одной длины
c = a + b
c

array([ 12,  24,  36,  48,  60,  72,  84,  96, 108])

In [72]:
#Поэлементное умножение массивов
c = a*b
c

array([  20,   80,  180,  320,  500,  720,  980, 1280, 1620])

In [77]:
#Вычисление средней величины
m = np.mean(c)
m

np.float64(633.3333333333334)

In [76]:
#Вычисление медианы
m = np.median(c)
m

np.float64(500.0)

In [79]:
#Минимальное и максимальное значения
print(np.min(a))
print(np.max(a))

2
18


In [81]:
#Вычисление дисперсии
d = np.var(a)
d

np.float64(26.666666666666668)

In [83]:
#Найти индекс числа с минимальным значением
m_i = np.argmin(a)
m_i

np.int64(0)